# Generated by Django 2.2.9 on 2020-04-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200409_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileClient',
            fields=[
                ('mobileUUID', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
