# Generated by Django 2.2.9 on 2020-04-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mobileclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileClient',
        ),
    ]
